client localhost {
    ipaddr      = 127.0.0.1
    secret      = testing123
    shortname   = localhost
    nas_type    = other
}

# Docker network icerisindeki herhangi bir container'dan gelen istekleri kabul et.
# 172.16.0.0/12 Docker'in default bridge network araligini kapsar.
client docker_network {
    ipaddr      = 172.16.0.0/12
    secret      = testing123
    shortname   = docker
    nas_type    = other
}